/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author kim
 */
public class Ventana extends javax.swing.JFrame {

    private Numeros num;
    
    private String num1, num2;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        num = new Numeros ();
        txtNum1.requestFocus();
    }
    
    public void leeNumeros (){
        num1 = txtNum1.getText();
        num2 = txtNum2.getText();
        
        num.setNum1( Double.parseDouble(num1) );
        num.setNum2( Double.parseDouble(num2) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCen = new javax.swing.JPanel();
        panIzq = new javax.swing.JPanel();
        btnMulti = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        panDer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        panSur = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        panNor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCen.setLayout(new javax.swing.BoxLayout(panCen, javax.swing.BoxLayout.X_AXIS));

        panIzq.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")), "Operaciones"));
        panIzq.setPreferredSize(new java.awt.Dimension(250, 200));
        panIzq.setLayout(new java.awt.GridLayout(2, 2));

        btnMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/a1.png"))); // NOI18N
        btnMulti.setText("Multiplicacion");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        panIzq.add(btnMulti);

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/a4.png"))); // NOI18N
        btnResta.setText("Resta");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        panIzq.add(btnResta);

        btnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/a3.png"))); // NOI18N
        btnDiv.setText("División");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        panIzq.add(btnDiv);

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/a2.png"))); // NOI18N
        btnSuma.setText("Suma");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        panIzq.add(btnSuma);

        panCen.add(panIzq);

        panDer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")), "Entrada"));
        panDer.setPreferredSize(new java.awt.Dimension(250, 205));
        panDer.setLayout(new javax.swing.BoxLayout(panDer, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Valor 1:");
        panDer.add(jLabel1);

        txtNum1.setText("0.0");
        panDer.add(txtNum1);

        jLabel2.setText("Valor 2:");
        panDer.add(jLabel2);

        txtNum2.setText("0.0");
        panDer.add(txtNum2);

        panCen.add(panDer);

        getContentPane().add(panCen, java.awt.BorderLayout.CENTER);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setText("Desarrollador: Jorguer1@gmail.com");
        panSur.add(jTextField1);

        getContentPane().add(panSur, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panNorLayout = new javax.swing.GroupLayout(panNor);
        panNor.setLayout(panNorLayout);
        panNorLayout.setHorizontalGroup(
            panNorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        panNorLayout.setVerticalGroup(
            panNorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panNor, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        leeNumeros();
        num.multiplicacion();
        num.Imprime();
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        leeNumeros();
        num.resta();
        num.Imprime();
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        leeNumeros();
        num.division();
        num.Imprime();
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        leeNumeros();
        num.suma();
        num.Imprime();
    }//GEN-LAST:event_btnSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panCen;
    private javax.swing.JPanel panDer;
    private javax.swing.JPanel panIzq;
    private javax.swing.JPanel panNor;
    private javax.swing.JPanel panSur;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
